# Generated by Django 3.0.10 on 2020-10-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField(max_length=25)),
                ('company_country', models.CharField(max_length=25)),
                ('company_state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Customer ', max_length=256)),
                ('address', models.TextField(blank=True, help_text='Enter address of customer or Company', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='Enter the city of the address', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='Enter the state of the address', max_length=50, null=True)),
                ('country', models.CharField(blank=True, help_text='Enter the country of the address', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Enter the email of the customer or                               Company', max_length=254, null=True)),
                ('mobile', models.EmailField(blank=True, help_text='Enter the Mobile of the customer or                               Company', max_length=254, null=True)),
                ('shiping_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(max_length=25)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('ship_to', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'PAID'), ('draft', 'UNPAID'), ('draft', 'DRAFT'), ('others', 'OTHERS')], max_length=10)),
                ('invoice_file', models.FileField(null=True, upload_to='')),
                ('invoice_note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('next_billing_date', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('digitized', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_manager.Company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_manager.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_manager.Invoice')),
            ],
        ),
    ]
