# Generated by Django 3.0.10 on 2020-10-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0002_auto_20201004_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_state',
            field=models.CharField(choices=[('processing', 'Processing'), ('digitized', 'Digitized'), ('failed', 'Failed')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('draft', 'UNPAID'), ('draft', 'DRAFT'), ('others', 'OTHERS')], default='draft', max_length=10),
        ),
    ]
