# Generated by Django 3.0.10 on 2020-10-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_manager', '0003_auto_20201005_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
